/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jtimer;

/**
 *
 * @author bozhin
 */
public class TimerDialog extends javax.swing.JDialog implements Runnable
{
    private int iHour;
    private int iMinutes;
    private int iSeconds;
    private int iMilliseconds;
    Thread th;
    private String fileName;

    /**
     * Creates new form TimerDialog
     */
    public TimerDialog(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        timeShowLabel.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        GetTime();
        jTextArea1.setText("");
        jButton1.setFocusable(true);
        th = new Thread(this, "xx");
        th.start();
    }
    
    private void GetTime()
    {
        long ltime = System.currentTimeMillis();
        iMilliseconds = (int) (ltime % 1000); ltime /= 1000;
        iSeconds = (int) (ltime % 60);        ltime /= 60;
        iMinutes = (int) (ltime % 60);        ltime /= 60;
        iHour = (int) (ltime % 24);
        timeShowLabel.setText(
                String.format("%1$02d:%2$02d:%3$02d:%4$03d",
                    iHour, iMinutes, iSeconds, iMilliseconds));
    }
    
    protected void finalize()
    {
        th.stop();
        th.destroy();
    }
    
    @Override
    public void run()
    {
        System.out.println("xxx");
        try
        {
            do
            {
                Thread.sleep(1);
                GetTime();
            } while (true);
        } catch (InterruptedException e)
        {
            System.out.println("Process exited.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeShowLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        getTimeMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        timeShowLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeShowLabel.setText("00:00:00:000");
        timeShowLabel.setToolTipText("Current time.");
        timeShowLabel.setFocusable(false);
        timeShowLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Get Time");
        jButton1.setToolTipText("Push this button to get current time\nin the list bellow.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");

        getTimeMenuItem.setMnemonic('g');
        getTimeMenuItem.setText("Get Time");
        getTimeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTimeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(getTimeMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        closeMenuItem.setMnemonic('q');
        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(timeShowLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeShowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        timeShowLabel.getAccessibleContext().setAccessibleName("timeShowLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String text = jTextArea1.getText();
        if (text.equals(""))
        {
            text = timeShowLabel.getText();
        }
        else
        {
            text += "\n" + timeShowLabel.getText();
        }
        jTextArea1.setText(text);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getTimeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTimeMenuItemActionPerformed
        String text = jTextArea1.getText();
        if (text.equals(""))
        {
            text = timeShowLabel.getText();
        }
        else
        {
            text += "\n" + timeShowLabel.getText();
        }
        jTextArea1.setText(text);
    }//GEN-LAST:event_getTimeMenuItemActionPerformed

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        
    }//GEN-LAST:event_saveMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TimerDialog dialog = new TimerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JMenuItem getTimeMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel timeShowLabel;
    // End of variables declaration//GEN-END:variables
}
