*
* File:   findesef.f
* Author: bozhin
*
* Created on Sun, 2012, Jan 22, 18:11
* Last modified 2012, Feb 3
*
      PROGRAM FIND_ES_EF
      IMPLICIT DOUBLEPRECISION(A-H,O-Z),INTEGER(I-N)
      DOUBLE PRECISION E(3), T(3), TEMP, EF
      DOUBLE PRECISION KELVIN, PI
      PARAMETER (KELVIN=1.D0/11604.D0)
      PARAMETER (PI=3.1415926535897932D0)
      COMMON /ETTEF/ E, T, TEMP, EF
C
      DOUBLE PRECISION SPARAM(13)
C
      DATA E /0.D0, 3.943D0, -1.D0/
      DATA T /1.5D0, 2.D0, 0.2D0/
      DATA SPARAM/1.74D0,2.44D0,0.72D0,0.87D0,0.66D0,0.62D0,
     *   0.59D0,0.33D0,0.33D0,0.39D0,0.38D0,0.36D0,0.94D0/
      TEMP=90.D0*KELVIN
      EF=1.543D0
      call setriang(0.d0,0.d0,pi,pi)
!      DJ=FINTEGRAL(1.543D0)
!      PRINT*,DJ
!      PRINT*
!      PRINT*
!      S=0.66D0
!      PRINT*,S
      DO I=1,13
         S=SPARAM(I)
         WRITE(UNIT=0,FMT=10)S
         CALL FINDESEF(S,ES,EFERMI)
         PRINT100,S,ES,EFERMI
      ENDDO
      STOP
   10 FORMAT('FIND_ES_EF: S=',F5.2)
  100 FORMAT(F4.2,1X,F7.3,1X,F7.3)
      END

      FUNCTION FINTEGRAL(EX)
      IMPLICIT NONE
      DOUBLE PRECISION FINTEGRAL,EX
      DOUBLE PRECISION DFERMI
      EXTERNAL DFERMI
      DOUBLE PRECISION RES,ERR,H
      INTEGER NEVALS,IFLAG
      DOUBLE PRECISION E(3), T(3), TEMP, EF
      DOUBLE PRECISION PI
      PARAMETER (PI=3.1415926535897932D0)
      COMMON /ETTEF/ E, T, TEMP, EF
      EF=EX
      call integ2d(DFERMI,0.d0,0.d0,pi,pi,1.d-4,res,nevals,iflag)
!      PRINT*,RES/(PI*PI),ERR,NEVALS,IFLAG
      FINTEGRAL=RES/(PI*PI)-0.34D0
      RETURN
      END
      
      FUNCTION DFERMI(PX,PY)
      IMPLICIT NONE
      DOUBLE PRECISION PX,PY,DIST,DFERMI
      DOUBLE PRECISION E(3), T(3), TEMP, EF
      INTEGER INFO
      COMMON /ETTEF/ E, T, TEMP, EF
      CALL fermi(px,py,Temp,Ef,e,t,dist,info)
      DFERMI=DIST
      IF (INFO.NE.0) PRINT 10,INFO
      RETURN
   10 FORMAT('DFERMI: ',I5)
      END

      SUBROUTINE FINDESEF(S,ES,EF)
      IMPLICIT NONE
      DOUBLE PRECISION S, ES, EF
      DOUBLE PRECISION FINTEGRAL
      EXTERNAL FINTEGRAL,SECANT
      LOGICAL IFPRINT
      INTEGER NMAX,ITER,IERR,I
      DOUBLE PRECISION RELERR,ABSERR
      DOUBLE PRECISION EF0,F0,EF1,F1
      DOUBLE PRECISION KELVIN, PI, ZERO
      PARAMETER (KELVIN=1.D0/11604.D0)
      PARAMETER (PI=3.1415926535897932D0)
      PARAMETER (ZERO=1.D-300)
      DOUBLE PRECISION E(3),T(3),TEMP,EFF
      COMMON /ETTEF/ E, T, TEMP, EFF
C
      TEMP=90*KELVIN
      NMAX=30
      RELERR=0.001D0
      ABSERR=0.001D0
      IFPRINT=.TRUE.
      EF=1.666D0
      ES = 4.D0*S*T(2)*T(2)/(EF-E(3))+EF
      E(2)=ES
      DO I=1,NMAX
         EF0=0.1D0
         EF1=2.0D0
         F0 =FINTEGRAL(EF0)
         F1 =FINTEGRAL(EF1)
         CALL SECANT(FINTEGRAL,NMAX,RELERR,ABSERR,EF0,F0,EF1,F1,
     *               EF,ITER,IFPRINT,IERR)
         ES = 4.D0*S*T(2)*T(2)/(EF-E(3))+EF
         
         WRITE(UNIT=0,FMT=100)I,ES,EF,ITER,IERR
         IF (DABS(ES).LT.ZERO) THEN
            IF (DABS(E(2)-ES).LT.ABSERR) RETURN
         ELSE
            IF (DABS(E(2)-ES)/DABS(ES).LT.RELERR) RETURN
         ENDIF
         E(2)=ES
      ENDDO
      WRITE(UNIT=0,FMT=200)
      RETURN
  100 FORMAT('FINDESEF: #',I2,1X,F7.3,1X,F7.3,1X,'ITERATIONS=',I2,
     *       1X,'FLAG=',I2)
  200 FORMAT('FINDESEF: MAXIMUM NUMBER OF ITERATIONS EXCEEDED')
      END
