C
C File:   xint2.f
C Author: bozhin
C
C Created on November 25, 2012, 9:21 PM
C
      SUBROUTINE XINTEG2(NX, NY, NZ, Y, Z, HX,
     *                   FDATA1, FDATA2, DINT1, DINT2)
      IMPLICIT NONE
      INTEGER NX, NY, NZ
      INTEGER X, Y, Z
      DOUBLEPRECISION FDATA1(NX, NY, NZ), FDATA2(NX, NY, NZ)
      DOUBLEPRECISION HX, DINT1, DINT2
      DOUBLEPRECISION C1, C2, C3
      PARAMETER (C1=1.D0/3.D0,C2=4.D0/3.D0,C3=2.D0/3.D0)
      DOUBLEPRECISION DSUM1, DSUM2
      DATA DSUM1, DSUM2 /0.D0, 0.D0/
      DSUM1 = C1 * (FDATA1(1,Y,Z)+FDATA1(NX,Y,Z))
     *      + C2 * FDATA1(NX-1,Y,Z)
      DSUM2 = C1 * (FDATA2(1,Y,Z)+FDATA2(NX,Y,Z))
     *      + C2 * FDATA2(NX-1,Y,Z)
      DO X = 2, NX-3, 2
         DSUM1 = DSUM1 + C2 * FDATA1(X,Y,Z)
     *                 + C3 * FDATA1(X+1,Y,Z)
         DSUM2 = DSUM2 + C2 * FDATA2(X,Y,Z)
     *                 + C3 * FDATA2(X+1,Y,Z)
      ENDDO
      DINT1 = HX * DSUM1
      DINT2 = HX * DSUM2
      RETURN
      END

      SUBROUTINE YINTEG2(NX, NY, NZ, Z, HX, HY,
     *                   FDATA1, FDATA2, DINT1, DINT2)
      IMPLICIT NONE
      INTEGER NX, NY, NZ
      INTEGER Y, Z
      DOUBLEPRECISION FDATA1(NX, NY, NZ), FDATA2(NX, NY, NZ)
      DOUBLEPRECISION HX, HY, DINT1, DINT2
      DOUBLEPRECISION C1, C2, C3
      PARAMETER (C1=1.D0/3.D0,C2=4.D0/3.D0,C3=2.D0/3.D0)
      DOUBLEPRECISION DSUM1, DSUM2
      DATA DSUM1, DSUM2 /0.D0, 0.D0/
      CALL XINTEG2(NX,NY,NZ, 1, Z, HX, FDATA1,FDATA2,DINT1,DINT2)
      DSUM1 = DINT1
      DSUM2 = DINT2
      CALL XINTEG2(NX,NY,NZ, NY, Z, HX, FDATA1,FDATA2,DINT1,DINT2)
      DSUM1 = C1 * (DSUM1 + DINT1)
      DSUM2 = C1 * (DSUM2 + DINT2)
      CALL XINTEG2(NX,NY,NZ, NY-1, Z, HX, FDATA1,FDATA2,DINT1,DINT2)
      DSUM1 = DSUM1 + C2 * DINT1
      DSUM2 = DSUM2 + C2 * DINT2
      DO Y = 2, NY-3, 2
      CALL XINTEG2(NX,NY,NZ, Y, Z, HX, FDATA1,FDATA2,DINT1,DINT2)
         DSUM1 = DSUM1 + C2 * DINT1
         DSUM2 = DSUM2 + C2 * DINT2
      CALL XINTEG2(NX,NY,NZ, Y+1, Z, HX, FDATA1,FDATA2,DINT1,DINT2)
         DSUM1 = DSUM1 + C3 * DINT1
         DSUM2 = DSUM2 + C3 * DINT2
      ENDDO
      DINT1 = HY * DSUM1
      DINT2 = HY * DSUM2
      RETURN
      END


      SUBROUTINE ZINTEG2(NX, NY, NZ, HX, HY, HZ,
     *                   FDATA1, FDATA2, DINT1, DINT2)
      IMPLICIT NONE
      INTEGER NX, NY, NZ
      INTEGER Z
      DOUBLEPRECISION FDATA1(NX, NY, NZ), FDATA2(NX, NY, NZ)
      DOUBLEPRECISION HX, HY, HZ, DINT1, DINT2
      DOUBLEPRECISION C1, C2, C3
      PARAMETER (C1=1.D0/3.D0,C2=4.D0/3.D0,C3=2.D0/3.D0)
      DOUBLEPRECISION DSUM1, DSUM2
      DATA DSUM1, DSUM2 /0.D0, 0.D0/
      CALL YINTEG2(NX,NY,NZ, 1, HX, HY, FDATA1,FDATA2,DINT1,DINT2)
      DSUM1 = DINT1
      DSUM2 = DINT2
      CALL YINTEG2(NX,NY,NZ, NZ, HX, HY, FDATA1,FDATA2,DINT1,DINT2)
      DSUM1 = C1 * (DSUM1 + DINT1)
      DSUM2 = C1 * (DSUM2 + DINT2)
      CALL YINTEG2(NX,NY,NZ, NZ-1, HX, HY, FDATA1,FDATA2,DINT1,DINT2)
      DSUM1 = DSUM1 + C2 * DINT1
      DSUM2 = DSUM2 + C2 * DINT2
      DO Z = 2, NZ-3, 2
      CALL YINTEG2(NX,NY,NZ, Z, HX, HY, FDATA1,FDATA2,DINT1,DINT2)
         DSUM1 = DSUM1 + C2 * DINT1
         DSUM2 = DSUM2 + C2 * DINT2
      CALL YINTEG2(NX,NY,NZ, Z+1, HX, HY, FDATA1,FDATA2,DINT1,DINT2)
         DSUM1 = DSUM1 + C3 * DINT1
         DSUM2 = DSUM2 + C3 * DINT2
      ENDDO
      DINT1 = HZ * DSUM1
      DINT2 = HZ * DSUM2
      RETURN
      END
