C ROOT FINDING SUBROUTINE
C NEWTON METHOD
      SUBROUTINE NEWTON(F,DF,X0,EPS,NMAX,ROOT,N)
C 'F'     -- INPUT; EXTERNAL; FUNCTION F(X)
C 'DF'    -- INPUT; EXTERNAL; DERIVATIVE OF FUNCTION F(X)
C 'X0'    -- INPUT; INITIAL GUESS
C 'EPS'   -- INPUT; ERROR ESTIMATION
C 'NMAX'  -- INPUT; MAXIMUM ADMISSIBLE NUMBER OF ITERATIONS
C 'ROOT'  -- OUTPUT; RETURNED APPROXIMATION TO THE ROOT
C 'N'     -- OUTPUT; RETURNED NUMBER OF ITERATIONS
      IMPLICIT NONE
      EXTERNAL F,DF
      DOUBLE PRECISION F,DF,X0,EPS,ROOT
      DOUBLE PRECISION X,DIFF
      INTEGER N,NMAX,I
      X=X0
      N=0
      DO I=1,NMAX
        N=N+1
        ROOT=X-F(X)/DF(X)
        DIFF=DABS(ROOT-X)
        IF(DIFF .LT. EPS) EXIT
        X=ROOT
      END DO
      RETURN
      END
