REM ---------------------------------------------------
REM
REM SEQ_FILE.BAS
REM
REM USE OF SEQUENTIAL FILE ACCESS COMMANDS
REM
REM AUTHOR: ANDRE MURTA
REM DATE: 20/12/1992
REM 
REM DEVELOPED AT CENTRO DE ENSINO SUPERIOR DO PARA
REM
REM ---------------------------------------------------
FALSE = 0
TRUE = 1
OPEN "mbasic.txt" FOR READING,SEQUENTIAL AS #1
OPEN "output.txt" FOR WRITING,SEQUENTIAL AS #2
10 FINPUT #1,$STR_VAL
   PRINT STR_VAL NONEWLINE
   IF (eof(1) = FALSE) THEN GOTO 10
CLOSE #1
FOR I=0 TO 10
   FPRINT #2,"Line: ";I
NEXT
CLOSE #2
END
