      PROGRAM NEUMDRV
C DRIVER PROGRAM TO TEST 'NEUMRND' SUBROUTINE
      IMPLICIT DOUBLE PRECISION(A-H,O-Z),INTEGER(I-N)
      PARAMETER (N=80000)
      DIMENSION X(N)
      EXTERNAL SDSIN
      DATA A,B,DU,DL /0.D0,3.1415D0,0.D0,1.D0/
      CALL NEUMRND(SDSIN,N,A,B,DU,DL,X,NN)
      DO I=1,N
      WRITE (UNIT=6,FMT=*,IOSTAT=IERR,ERR=100) X(I)
      ENDDO
      WRITE(UNIT=0,FMT=*,IOSTAT=IERR,ERR=200) NN
      STOP
 100  STOP 'ERROR EXPORTING DATA X'
 200  STOP 'ERROR EXPORTING DATA NN'
      END

      SUBROUTINE SDSIN(X,Z)
      IMPLICIT NONE
      DOUBLE PRECISION X,Z,DSIN
      INTRINSIC DSIN
      Z=DSIN(X)
      RETURN
      END
