C
C File:   xint2d.for
C Author: bozhin
C
C Created on December 5, 2012, 9:17 PM
C
      SUBROUTINE XINTEG(NX, NY, Y, HX, FDATA1, DINT1)
      IMPLICIT NONE
      INTEGER NX, NY
      INTEGER X, Y
      DOUBLEPRECISION FDATA1(NX, NY)
      DOUBLEPRECISION HX, DINT1
      DOUBLEPRECISION C1, C2, C3
      PARAMETER (C1=1.D0/3.D0,C2=4.D0/3.D0,C3=2.D0/3.D0)
      DOUBLEPRECISION DSUM1
      DATA DSUM1 /0.D0/
      DSUM1 = C1 * (FDATA1(1,Y)+FDATA1(NX,Y))
     *      + C2 * FDATA1(NX-1,Y)
      DO X = 2, NX-3, 2
         DSUM1 = DSUM1 + C2 * FDATA1(X,Y)
     *                 + C3 * FDATA1(X+1,Y)
      ENDDO
      DINT1 = HX * DSUM1
      RETURN
      END

      SUBROUTINE YINTEG(NX, NY, HX, HY, FDATA1, DINT1)
      IMPLICIT NONE
      INTEGER NX, NY
      INTEGER Y
      DOUBLEPRECISION FDATA1(NX, NY)
      DOUBLEPRECISION HX, HY, DINT1
      DOUBLEPRECISION C1, C2, C3
      PARAMETER (C1=1.D0/3.D0,C2=4.D0/3.D0,C3=2.D0/3.D0)
      DOUBLEPRECISION DSUM1
      DATA DSUM1 /0.D0/
      CALL XINTEG(NX, NY, 1, HX, FDATA1, DINT1)
      DSUM1 = DINT1
      CALL XINTEG(NX, NY, NY, HX, FDATA1, DINT1)
      DSUM1 = C1 * (DSUM1 + DINT1)
      CALL XINTEG(NX, NY, NY-1, HX, FDATA1, DINT1)
      DSUM1 = DSUM1 + C2 * DINT1
      DO Y = 2, NY-3, 2
         CALL XINTEG(NX, NY, Y, HX, FDATA1, DINT1)
         DSUM1 = DSUM1 + C2 * DINT1
         CALL XINTEG(NX, NY, Y+1, HX, FDATA1, DINT1)
         DSUM1 = DSUM1 + C3 * DINT1
      ENDDO
      DINT1 = HY * DSUM1
      RETURN
      END

