      PROGRAM XINTEG2TEST
      IMPLICIT NONE
      INTEGER NX, NY, NXH, NYH
      PARAMETER (NX=31,NY=31)
      PARAMETER (NXH=NX/2,NYH=NY/2)
      DOUBLEPRECISION FDATA(-NXH:NXH,-NYH:NYH)
      DOUBLEPRECISION FUNC
      DOUBLEPRECISION HX, HY, X, Y, DINTEG
      DOUBLEPRECISION XMIN,XMAX,YMIN,YMAX
      PARAMETER (XMIN=-5.D0,XMAX=5.D0,YMIN=-5.D0,YMAX=5.D0)
      INTEGER I, J
      HX = (XMAX-XMIN)/DFLOAT(NX-1)
      HY = (YMAX-YMIN)/DFLOAT(NY-1)
      DO I = -NXH, NXH
         X = DFLOAT(I)*HX
         DO J = -NYH, NYH
            Y = DFLOAT(J)*HY
            FDATA(I,J)=FUNC(X, Y)
         ENDDO
      ENDDO
      CALL YINTEG(NX, NY, HX, HY, FDATA, DINTEG)
      PRINT*,DINTEG
      PAUSE
      END
      
      DOUBLEPRECISION FUNCTION FUNC(X,Y)
      IMPLICIT NONE
      DOUBLEPRECISION X, Y
      FUNC = DEXP(-X*X-Y*Y)
      END
