C NEUMRND - GENERATES RANDOM DISTRIBUTIONS USING VON NEUMANN ALGORITHM
C
       SUBROUTINE NEUMRND(DIST,N,A,B,DU,DL,X,NN)
C
C 'DIST'-INPUT. DISTRIBUTION FUNCTION. 'SUBROUTINE DIST(X,RESULT)'
C 'N'   -INPUT. REQUIRED NUMBER OF POINTS TO GENERATE
C 'A'   -INPUT. LEFT BORDER OF VALUES
C 'B'   -INPUT. RIGHT BORDER OF VALUES
C 'DU'  -INPUT. UPPER BOUNDARY OF POINTS TO GENERATE
C 'DL'  -INPUT. LOWER BOUNDARY OF POINTS TO GENERATE
C 'X'   -OUTPUT. GENERATED POINTS
C 'NN'  -OUTPUT. NUMBER OF GENERATED POINTS
       IMPLICIT DOUBLE PRECISION(A-H,O-Z),INTEGER(I-N)
       EXTERNAL DIST
       DIMENSION X(N)
       NN = 0
       I  = 1
       XM = B-A
       YM = DU-DL
       DO WHILE (I.LE.N)
          X0 = XM * RAND() + A
          Y0 = YM * RAND() + DL
          NN = NN + 1
          CALL DIST(X0, Z0)
          IF (Y0.LE.Z0) THEN
             X(I) = X0
             I    = I + 1
          ENDIF
       ENDDO
       RETURN
       END
