      PROGRAM WINFILEEXT
C
C THIS PROGRAM READS A FILE WITH SPECIFIED EXTENSIONS AND
C DESCRIPTIONS AND GENERATES .REG FILE, ASSOCIATING THESE
C FILES WITH NOTEPAD.EXE
C
C IFILE   -- INPUT FILE NAME
C OFILE   -- OUTPUT FILE NAME. YOU MUST SPECIFY THE EXTENSION .REG
C EXT     -- EXTENSION TO BE ASSOCIATED WITH NOTEPAD.EXE. IT MUST NOT BEGINS WITH DOT
C DESCR   -- DESCRIPTION FOR THE FILE TYPE
C COMMENT -- COMMENT
C
C THE STRUCTURE OF THE INPUT FILE MUST BE EXT // DESCR // COMMENT
C WHERE // MEANS NEW LINE
C NO SPECIAL BEGINNING OR ENDING OF FILE IS REQUIRED
C
      CHARACTER*256 IFILE, OFILE
      CHARACTER*256 EXT
      CHARACTER*256 DESCR
      CHARACTER*256 COMMENT
      CHARACTER*1   ANS
      CHARACTER*11  FMTC
      CHARACTER*50  FMTD
      CHARACTER*256 FMTEXT
      
   10 PRINT*, 'ENTER THE INPUT FILE NAME'
      READ*, IFILE
      OPEN (UNIT=10,FILE=IFILE,STATUS='OLD',IOSTAT=IERR)
      IF (IERR.NE.0) THEN
         PRINT*,'THE FILE ', IFILE, ' DOES NOT EXIST'
         PRINT*,'DO YOU WANT TO TRY AGAIN? Y/N [N]:'
         READ*,ANS
         IF (ANS.EQ.'Y'.OR.ANS.EQ.'y') GOTO 10
         STOP 'INPUT FILE WAS INVALID'
      ENDIF
C
   20 PRINT*, 'ENTER THE OUTPUT FILE NAME'
      READ*, OFILE
      OPEN (UNIT=11,FILE=OFILE,STATUS='REPLACE',IOSTAT=IERR)
      IF (IERR.NE.0) THEN
         PRINT*,'THE FILE ', OFILE, ' COULD NOT BE CREATED'
         PRINT*,'DO YOU WANT TO TRY AGAIN? Y/N [N]:'
         READ*,ANS
         IF (ANS.EQ.'Y'.OR.ANS.EQ.'y') GOTO 20
         STOP 'OUPUT FILE WAS INVALID'
      ENDIF
      
      WRITE(UNIT=11,FMT=100,IOSTAT=IERR)
      IF (IERR.NE.0) THEN
         PRINT 90
         GOTO 40
      ENDIF
      DO
         READ(UNIT=10,FMT=*,IOSTAT=IERR,ERR=29,END=30) EXT
         READ(UNIT=10,FMT=*,IOSTAT=IERR,END=30) DESCR
         READ(UNIT=10,FMT=*,IOSTAT=IERR,END=30) COMMENT
         CALL CANTRIM1(EXT,NEXT)
         CALL CANTRIM(COMMENT,NCOM)
         CALL CANTRIM(DESCR,NDESCR)
C
               WRITE(UNIT=FMTEXT,FMT=99) NEXT
         PRINT FMTEXT, EXT
C
               WRITE(UNIT=FMTC,FMT=101) NCOM
         WRITE(UNIT=11,FMT=FMTC,IOSTAT=IERR) COMMENT
C
              WRITE(UNIT=FMTEXT,FMT=102) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
              WRITE(UNIT=FMTEXT,FMT=103) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
         WRITE(UNIT=11,FMT=104,IOSTAT=IERR)
              WRITE(UNIT=FMTEXT,FMT=105) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
              WRITE(UNIT=FMTD,FMT=106) NDESCR
         WRITE(UNIT=11,FMT=FMTD,IOSTAT=IERR) DESCR
              WRITE(UNIT=FMTEXT,FMT=107) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
         WRITE(UNIT=11,FMT=108,IOSTAT=IERR)
              WRITE(UNIT=FMTEXT,FMT=109) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
         WRITE(UNIT=11,FMT=110,IOSTAT=IERR)
              WRITE(UNIT=FMTEXT,FMT=111) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
              WRITE(UNIT=FMTEXT,FMT=112) NEXT
         WRITE(UNIT=11,FMT=FMTEXT,IOSTAT=IERR) EXT
         WRITE(UNIT=11,FMT=113,IOSTAT=IERR)
      ENDDO
   29 PRINT 91
      GOTO 40
   30 CONTINUE
      WRITE(UNIT=11,FMT=200,IOSTAT=IERR)
   40 CLOSE(UNIT=11)
   50 CLOSE(UNIT=10)
      STOP
   90 FORMAT('CANNOT WRITE TO OUTPUT FILE')
   91 FORMAT('CANNOT READ FROM INPUT FILE ',
     * 'OR DATA IS INVALID TYPE')
   99 FORMAT('(A',I3.3,')')
  100 FORMAT('Windows Registry Editor Version 5.00',//)
  101 FORMAT('("; ",A',I3.3,')')
  102 FORMAT('(''[HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\.'',A',
     1       I3.3,','']'')')
  103 FORMAT('(''@="'',A',I3.3,',''file"'')')
  104 FORMAT('"PerceivedType"="text"',/,
     1       '"Content Type"="text/plain"',/)
  105 FORMAT('(''[HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\'',A',
     1       I3.3,',''file]'')')
  106 FORMAT('(''@="'',A',I3.3,',''"'',/)')
  107 FORMAT('(''[HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\'',A',
     1       I3.3,'''file\\DefaultIcon]'')')
  108 FORMAT('@="%SystemRoot%\\\\system32\\\\SHELL32.dll,70"',/)
  109 FORMAT('(''[HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\'',A',
     1       I3.3,'''file\\shell]'')')
  110 FORMAT('@=""',/)
  111 FORMAT('(''[HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\'',A',
     1       I3.3,'''file\\shell\\open]'',/)')
  112 FORMAT('(''[HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\'',A',
     1       I3.3,'''file\\shell\\open\\command]'')')
  113 FORMAT('@="notepad.exe %1"',//)
  200 FORMAT('; END OF FILE')
      END

      SUBROUTINE CANTRIM(WORD, LENGTH)
C END OF THE STRING MEANS TWO SEQUAL SPACES
      CHARACTER*256 WORD
      CHARACTER*1 CH(256)
      INTEGER LENGTH
      INTEGER I
      LENGTH = 0
      READ(UNIT=WORD,FMT='(256A1)',IOSTAT=IERR,ERR=10,END=10) CH
      DO I=2,256
         IF (CH(I-1).EQ.' '.AND.CH(I).EQ.' ') RETURN
         LENGTH = LENGTH + 1
      ENDDO
   10 CONTINUE
      RETURN
      END
      
      SUBROUTINE CANTRIM1(WORD, LENGTH)
C END OF THE STRING MEANS TWO SEQUAL SPACES
      CHARACTER*256 WORD
      CHARACTER*1 CH(256)
      INTEGER LENGTH
      INTEGER I
      LENGTH = 0
      READ(UNIT=WORD,FMT='(256A1)',IOSTAT=IERR,ERR=10,END=10) CH
      DO I=1,256
         IF (CH(I).EQ.' ') RETURN
         LENGTH = LENGTH + 1
      ENDDO
   10 CONTINUE
      RETURN
      END
