C FILE: FRACRAD.FOR
C THIS PROGRAM CALCULATES THE FRACTAL DIMESION
C OF AN ARRAY USING THE RADIUS OF GIRATION METHOD
      PROGRAM FRACRAD
      INTEGER NMAX
      PARAMETER(NMAX=40 000)
C FILE UNITS: UIN UOUT
      INTEGER UIN, UOUT
      PARAMETER (UIN=12, UOUT=14)
C DLR - CONTAINS THE LOGARITHMS OF GIRATION RADUISES
C DLN - CINTAINS THE LOGARITHMS OF N 
      DOUBLE PRECISION DLR(3,NMAX), DLN(NMAX)
      INTEGER N, NN, ICURRENT, I
      INTEGER IX, IY, IR(2,NMAX)
C RX - X-COMPONENT OF THE MEAN RADIUS
C RY - Y-COMPONENT OF THE MEAN RADIUS
      DOUBLE PRECISION DI, RX, RY
      DOUBLE PRECISION A, B, DNN
      DOUBLE PRECISION SX, SY, SXX, SXY
C FNAMEI - NAME OF INPUT FILE
C FNAMEO - NAME OF OUTPUT FILE
      CHARACTER*255 FNAMEI, FNAMEO
      CHARACTER*255 ARG
      IF (IARGC() .LT. 2) THEN
         CALL GETARG(0, ARG)
         PRINT*,'USAGE: ', ARG, '<IN FILE> <OUT FILE>'
         STOP
      ENDIF
C
C     READS COMMAND-LINE ARGUMENTS
      CALL GETARG(1, FNAMEI)
      CALL GETARG(2, FNAMEO)
C
C     OPEN INPUT AND OUTPUT FILES
      OPEN(UNIT=UIN,FILE=FNAMEI,STATUS='OLD',ERR=1000)
C
C     READ INPUT DATA
      N=0
      ICURRENT=0
      DO
         READ(UNIT=UIN,FMT=500,IOSTAT=IERR,ERR=10,END=10) IX, IY
         ICURRENT=ICURRENT+1
         N=N+1
         IF (N.GT.NMAX) GOTO 2000
         IR(1,N) = IX
         IR(2,N) = IY
      ENDDO
   10 CONTINUE
C
C     CLOSE INPUT DATA FILE
      CLOSE(UNIT=UIN,ERR=1002)
      PRINT*,N
C
C     CALCULATION OF RADIUS OF GYRATION
      DLR(2,1) = DFLOAT(IR(1,1))
      DLR(3,1) = DFLOAT(IR(2,1))
      DLR(1,1) = DLR(2,1)**2 + DLR(3,1)**2
      DO I = 2, N
         RX = DFLOAT(IR(1,I))
         RY = DFLOAT(IR(2,I))
         DLR(1,I) = DLR(1,I-1) + (RX**2+RY**2)
         DLR(2,I) = DLR(2,I-1) + RX
         DLR(3,I) = DLR(3,I-1) + RY
      ENDDO
      DO I = 2, N
         DI = DFLOAT(I)
         DLR(2,I)=DLR(2,I)/DI
         DLR(3,I)=DLR(3,I)/DI
         DLR(1,I)=DLR(1,I)/DI-(DLR(2,I)**2+DLR(3,I)**2)
         DLR(1,I)=DLOG(DLR(1,I))
         DLN(I) = DLOG(DI)
      ENDDO
C
C     OPEN OUTPUT FILES
      OPEN(UNIT=UOUT,FILE=FNAMEO,STATUS='REPLACE',ERR=1001)
      DI = 200
      DO I = DI, N, DI
         WRITE(UNIT=UOUT,FMT=510,ERR=910) DLN(I),DLR(1,I)
      ENDDO
C
C     CLOSE OUTPUT FILES
      CLOSE(UNIT=UOUT,ERR=1003)
C
C     CALCULATION OF FRACTAL DIMANSION
      NN = (N-DI)
      DNN = DFLOAT(NN)
      SX  = 0.D0
      SY  = 0.D0
      SXY = 0.D0
      SXX = 0.D0
      DO I = DI, N
         SX  = SX  + DLN(I)
         SY  = SY  + DLR(1,I)
         SXX = SXX + DLN(I)*DLN(I)
         SXY = SXY + DLN(I)*DLR(1,I)
      ENDDO
      A=(SX*SY-DNN*SXY)/(SX*SX-DNN*SXX)
      B=(SY-A*SX)/DNN
      PRINT*,'A=',A
      PRINT*,'B=',B
C
      STOP
  500 FORMAT(I3,1X,I6)
  510 FORMAT(E16.7,1X,E16.7)
  900 PRINT*,'ERROR READING INPUT FILE'
      GOTO 5100
  910 PRINT*,'ERROR WRITING DATA'
      GOTO 5100
 1000 PRINT*,'ERROR: CANNOT OPEN INPUT FILE ', FNAMEI
      GOTO 5000
 1001 PRINT*,'ERROR: CANNOT OPEN OUTPUT FILE ', FNAMEO
      GOTO 5000
 1002 PRINT*,'ERROR: CANNOT CLOSE INPUT FILE ', FNAMEI
      GOTO 5000
 1003 PRINT*,'ERROR: CANNOT CLOSE OUTPUT FILE ', FNAMEO
      GOTO 5000
 2000 PRINT*,'DATA ARRAYS ARE TOO SHORT FOR THIS DATA FILE'
      PRINT*,'INCRENENT THE NMAX PARAMETER AND TRY AGAIN'
      GOTO 5100
 5000 STOP 'IO ERROR'
 5100 STOP 'DATA ERROR'
      END
      
      SUBROUTINE LSQ(LEFT,RIGHT,STEP,X,Y,A,B)
      INTEGER I, LEFT, RIGHT, STEP, N
      DOUBLEPRECISION X(*), Y(*), A, B
      DOUBLEPRECISION SX, SY, SXY, SXX, DN
      N   = (RIGHT-LEFT)/STEP
      DN  = DFLOAT(N)
      SX  = 0.D0
      SY  = 0.D0
      SXY = 0.D0
      SXX = 0.D0
      DO I = LEFT, RIGHT, STEP
         SX  = SX  + X(I)
         SY  = SY  + Y(I)
         SXY = SXY + X(I)*Y(I)
         SXX = SXX + X(I)*X(I)
      ENDDO
      A=(SX*SY-DN*SXY)/(SX*SX-DN*SXX)
      B=(SY-A*SX)/DN
      RETURN
      END
