      SUBROUTINE TEST
C     THIS PROGRAM TESTS THE SUBROUTINE CSPLINE
      IMPLICIT NONE
C MAXIMUM COEFFICIENT FOR DATA POINTS
      INTEGER N
      PARAMETER (N = 18)
c EXTERNAL FUNCTION
      EXTERNAL F
      DOUBLEPRECISION F
C LOCAL VARIABLES
      INTEGER  ERROR, I
      DOUBLEPRECISION X(N), Y(N)
      DOUBLEPRECISION A(N-1), B(N-1), C(N-1), D(N-1)
C     HELPER ARRAYS
      DOUBLEPRECISION H(N-1)
      DOUBLEPRECISION T(N), U(N), V(N), W(N)
C     VARIABLES FOR CHECKING ALGORITHM
      DOUBLEPRECISION Z, YZ
C     SET X-VALUES
      DATA X  / -2.95D0, -2.60D0, -2.10D0, -1.80D0, -1.40D0, -1.0D0,
     *          -0.75D0, -0.30D0, -0.05D0,  0.20D0,  0.55D0,  0.90D0,
     *           1.25D0,  1.60D0,  1.70D0,  2.10D0,  2.40D0,  3.00D0 /
C CALCULATE Y-COORDINATES CORRESPONDING TO DATA VALUES OF X
      DO I = 1, N
         Y(I) = F(X(I))
      ENDDO
C********************************************************************
C CALL CUBIC_SPLINE TO FIT A SET OF N POLYNOMIALS
      CALL CSPLINE(N, X, Y, A, B, C, D, H, T, U, V, W, ERROR)
      IF (ERROR .NE. 0) THEN
         PRINT*, 'ERROR ', ERROR
         STOP
      ENDIF
C********************************************************************
C NOW COMPARE INTERPOLATED VALUES WITH TRUE
C ONES USING EVENLY SPACED SET OF VALUES
C BETWEEN -2.8 AND  +2.8
*      PRINT 41
      DO I = 1, 15
C CALCULATE Z (THE VALUE TO BE USED)
         Z = -2.8D0 + 0.4D0*(I-1)
         CALL CUBSPL(YZ, Z, N, X, A, B, C, D)
C PRINT COMPARATIVE RESULTS
         PRINT 40, Z, F(Z), YZ
      ENDDO
      STOP
   40 FORMAT(6X,F6.2,2F15.6)
   41 FORMAT(//,9X,'X',5X,'EXP(-0.5X**2)',3X,'SPLINE VALUE',//)
      END
